name: auto grow grass

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  auto-grow-grass:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: auto push
        run: | 
          echo "w" >> README.md
          git config --local user.name ${{ secrets.USER_NAME }}
          git config --local user.email ${{ secrets.USER_EMAIL }}
          git add .
          git commit -m "w"
          git push -u origin main
